//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecIFicator.DefaultPlugin.Resources.BlazorComponents.MetadataEditor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataImporter___Kopieren {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataImporter___Kopieren() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecIFicator.DefaultPlugin.Resources.BlazorComponents.MetadataEditor.DataImporter" +
                            " - Kopieren", typeof(DataImporter___Kopieren).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string Button_Import {
            get {
                return ResourceManager.GetString("Button.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select file... ähnelt.
        /// </summary>
        internal static string Button_SelectFile {
            get {
                return ResourceManager.GetString("Button.SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error downloading data. ähnelt.
        /// </summary>
        internal static string Error_Download {
            get {
                return ResourceManager.GetString("Error.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error importing data. ähnelt.
        /// </summary>
        internal static string Error_ImportError {
            get {
                return ResourceManager.GetString("Error.ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error parsing SpecIF data. ähnelt.
        /// </summary>
        internal static string Error_SpecIfParsing {
            get {
                return ResourceManager.GetString("Error.SpecIfParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SpecIF 1.1 - Released ähnelt.
        /// </summary>
        internal static string File_SpecIF1_1Release {
            get {
                return ResourceManager.GetString("File.SpecIF1_1Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SpecIF 1.2 - Development ähnelt.
        /// </summary>
        internal static string File_SpecIF1_2Dev {
            get {
                return ResourceManager.GetString("File.SpecIF1_2Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SpecIF 1.2 - Development, Non normative ähnelt.
        /// </summary>
        internal static string File_SpecIF1_2DevNonNormative {
            get {
                return ResourceManager.GetString("File.SpecIF1_2DevNonNormative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metadata on GitHub ähnelt.
        /// </summary>
        internal static string Label_FromGithub {
            get {
                return ResourceManager.GetString("Label.FromGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import SpecIF data ähnelt.
        /// </summary>
        internal static string Label_ImportData {
            get {
                return ResourceManager.GetString("Label.ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import data from SpecIF file ähnelt.
        /// </summary>
        internal static string Label_ImportFromFile {
            get {
                return ResourceManager.GetString("Label.ImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import data from URL (download) ähnelt.
        /// </summary>
        internal static string Label_ImportFromURL {
            get {
                return ResourceManager.GetString("Label.ImportFromURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing selected ähnelt.
        /// </summary>
        internal static string Label_NothingSelected {
            get {
                return ResourceManager.GetString("Label.NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override existing elements with same key ähnelt.
        /// </summary>
        internal static string Label_OverrideExisting {
            get {
                return ResourceManager.GetString("Label.OverrideExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading data... ähnelt.
        /// </summary>
        internal static string Message_Downloading {
            get {
                return ResourceManager.GetString("Message.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing data... ähnelt.
        /// </summary>
        internal static string Message_ImportingData {
            get {
                return ResourceManager.GetString("Message.ImportingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data successfully imported. ähnelt.
        /// </summary>
        internal static string Message_ImportSuccess {
            get {
                return ResourceManager.GetString("Message.ImportSuccess", resourceCulture);
            }
        }
    }
}
